### ISSUE TITLE
Mixin Prepare Failing

### ISSUE THREAD

**Issue by LucasCur** [Globox1997/LibZ#1]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.23

### Mod Version

Tried 1.01 and 1.02

### Describe the Issue

When using LibZ, I get this recurring problem which results in random errors being thrown from other mods, which before had no issues.

### latest.log

https://gist.github.com/LucasCur/52a5611c15fbd4e3b9ee9afb44a359a9

### Do you use any other mods except the required ones?

yes

**Comment by LucasCur** [comment]
Game still crashes on 1.0.0 but no errors are produced

**Comment by Globox1997** [comment]
How to reproduces this bug?
