### ISSUE TITLE
Crash on start with tierify

### ISSUE THREAD

**Issue by agentsteven** [Globox1997/LibZ#3]
### Minecraft Version

1.20.x

### Mod Loader Version

0.15.10

### Mod Version

libz 1.0.3+1.20.1 and tierify 1.1.0

### Describe the Issue

I made a custom modpack, and for some reason when i add tierify to it, it crashes on start. and even when i added libz, it still kept cr

### latest.log

[2024-05-07-6.log.gz](https://github.com/Globox1997/LibZ/files/15242653/2024-05-07-6.log.gz)

**Comment by Globox1997** [comment]
I recommend to use TieredZ, for whatever reason someone forked it.
